server:
  port: 8081
  servlet.context-path: /api/v1

spring.application.name: conversation-service

#External ChatGPT API
chat-gpt.api:
  url: https://api.openai.com/v1
  key: ${chat-gpt-api.key} #Paste here your ChatGPT api key


logging.level:
  pl.piter.conversation.adapter.chatgpt.client: DEBUG