version: "3.8"

volumes:
  mongodb_data:
    driver: local

services:
  mongodatabase:
    image: mongo:latest
    container_name: "mongodatabase"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "user"
      MONGO_INITDB_ROOT_PASSWORD: "password123"
      MONGO_INITDB_DATABASE: "conversations"
    volumes:
      - mongodb_data:/data/db